# vim:ft=kitty

## name: shibui raised
## author: eureka-cpu · https://github.com/eureka-cpu
## license: MIT
## blurb: A quieter cut of ai — same ground (scroll, kimono, tatami), but
##   with the accents desaturated and deepened toward ferra's restraint.
##   Named for shibui (渋い), the subdued, unobtrusive beauty in traditional
##   Japanese aesthetics. Raised surface variant.

# The cursor color
cursor #9ea7ba

# The foreground color
foreground #d2cbad

# The background color
background #272c35

# The foreground for selections
selection_foreground #d2cbad

# The background for selections
selection_background #353b4a

# The 16 terminal colors. There are 8 basic colors, each color has a dull and
# bright version.

# black
color0   #191a20
color8   #535a6b

# red
color1   #b26461
color9   #c88e8a

# green
color2   #939971
color10  #aeb393

# yellow
color3   #b39b6a
color11  #c8b18b

# blue
color4   #9ea7ba
color12  #b7bfce

# magenta
color5   #b194af
color13  #997a96

# cyan
color6   #709994
color14  #8ab1ab

# white
color7   #b0a89c
color15  #dad6c9

active_tab_foreground   #d2cbad
active_tab_background   #2f3440
inactive_tab_foreground #b0a89c
inactive_tab_background #272c35
