# vim:ft=kitty

## name: shibui gamma corrected
## author: eureka-cpu · https://github.com/eureka-cpu
## license: MIT
## blurb: Gamma-corrected variant -- ICC-shifted so kitty renders the same
##   perceived values as the browser shows for the base theme on a wide-gamut
##   display. Base: A quieter cut of ai — same ground (scroll, kimono, tatami), but
##   with the accents desaturated and deepened toward ferra's restraint.
##   Named for shibui (渋い), the subdued, unobtrusive beauty in traditional
##   Japanese aesthetics.

# The cursor color
cursor #99a2b2

# The foreground color
foreground #cbc4a7

# The background color
background #24262b

# The foreground for selections
selection_foreground #cbc4a7

# The background for selections
selection_background #363a46

# The 16 terminal colors. There are 8 basic colors, each color has a dull and
# bright version.

# black
color0   #1e1f24
color8   #515869

# red
color1   #ad625e
color9   #c28a86

# green
color2   #8e946f
color10  #a9ad8f

# yellow
color3   #ae9668
color11  #c2ab87

# blue
color4   #99a2b2
color12  #b2b9c3

# magenta
color5   #ac90a9
color13  #947792

# cyan
color6   #6c9490
color14  #85aba6

# white
color7   #aba398
color15  #d3cfbf

active_tab_foreground   #cbc4a7
active_tab_background   #2b2f37
inactive_tab_foreground #aba398
inactive_tab_background #24262b
